### ISSUE TITLE
Plugin not working?

### ISSUE THREAD

**Issue by NicolaIsotta** [stephanrauh/JSFLibraryGenerator#5]
Hi @stephanrauh, I've installed the plugin in Eclipse (the OSGi console says it's active), but I don't see the context menu for the .jsfdl file. Am I doing something wrong?
Screenshot of my Eclipse: https://postimg.org/image/mzdnt61b1/

**Comment by stephanrauh** [comment]
Cool! Try the package explorer. I didn't implement the context menu in the project explorer.

**Comment by NicolaIsotta** [comment]
Yep, that was the problem. It's been probably four years since the last time I used Eclipse.

**Comment by stephanrauh** [comment]
Newer versions of XText also run in IntelliJ or even as a stand-alone program. It might be a good idea to implement a Maven plugin. It's a pity that I don't have enough spare time to do this. Any volunteers?

**Comment by stephanrauh** [comment]
I've uploaded a new version of the plugin that fixes a few bugs and adds the missing menu entry to the project explorer's context menu.
